package com.movie.presentation.ui.theme

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val ZERO_SIZE = 0.dp
val VERY_VERY_TINY_SIZE = 1.dp
val DEFAULT_PADDING_VERY_VERY_SMALL_SIZE = 4.dp
val DEFAULT_PADDING_VERY_SMALL_SIZE = 6.dp
val DEFAULT_PADDING_SMALL_SIZE = 8.dp
val DEFAULT_PADDING_MEDIUM_SIZE = 10.dp
val DEFAULT_PADDING_LARGE_SIZE = 12.dp
val DEFAULT_PADDING_EXTRA_LARGE_SIZE = 16.dp
val DEFAULT_PADDING_VERY_LARGE_SIZE = 20.dp
val DEFAULT_PADDING_VERY_VERY_LARGE_SIZE = 24.dp
val SIZE_150_DP = 150.dp
val SIZE_180_DP = 180.dp
val SIZE_240_DP = 240.dp

val DEFAULT_FONT_EXTRA_LARGE_SIZE = 16.sp
val DEFAULT_FONT_VERY_LARGE_SIZE = 18.sp
